---
parent: 'common/test_cases/origin_built_release.yml'
extensions:
  actions:
    - type: "script"
      title: "pull image for oc binary"
      repository: "origin"
      script: |-
        sudo docker pull openshift/origin:v3.9
        sudo docker create --name temp-container openshift/origin:v3.9
        sudo docker cp temp-container:/usr/bin/oc ./
        sudo docker rm temp-container
        sudo mv -f ./oc /bin/oc
    - type: "script"
      title: "start openshift server"
      repository: "origin"
      script: |-
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
        sudo yum install ./google-chrome-stable_current_*.rpm -y
        oc version
        oc cluster up --public-hostname=localhost --loglevel=5 --server-loglevel=5
    - type: "script"
      title: "run web console tests"
      repository: "origin-web-console"
      script: |-
        export PATH=$PATH:$(pwd)/node_modules/.bin
        make test
  post_actions:
    - type: "script"
      title: "grab container logs"
      repository: "origin"
      script: |-
        trap 'exit 0' EXIT
        ( source hack/lib/init.sh; os::cleanup::dump_container_logs )
  artifacts:
    - "/data/src/github.com/openshift/origin-web-console/test/tmp/screenshots/"
    - "/data/src/github.com/openshift/origin-web-console/test/coverage/"
    - "/data/src/github.com/openshift/origin-web-console/test/junit/"
    - "/data/src/github.com/openshift/origin-web-console/test/reports/"
