---
parent: 'test_cases/test_pull_request_origin_aggregated_logging_journald.yml'
overrides:
  sync:
    - "openshift,origin=release-3.9"
    - "openshift,aos-cd-jobs=master"
    - "openshift,image-registry=release-3.9"
    - "openshift,openshift-ansible=release-3.9"
    - "openshift,kubernetes-metrics-server=release-3.9"
    - "openshift,origin-web-console-server=release-3.9"
  evars: "-e@/data/src/github.com/openshift/origin-aggregated-logging/ci-ansible-common.yaml -e@/data/src/github.com/openshift/origin-aggregated-logging/ci-ansible-journald.yaml"
